2025-06-21 15:00:03,781 - __main__ - INFO - Aplicación PyQt6 inicializada
2025-06-21 15:00:03,781 - core.database.connection - ERROR - Error creando pool de conexiones: Connection configuration not valid: Unsupported argument 'read_timeout'
2025-06-21 15:00:11,294 - __main__ - INFO - Recursos limpiados correctamente
